spring:
  application:
    name: liulei-spring-cloud-feign
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
server:
  port: 7901
eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true