server:
  port: 8888
spring:
  application:
    name: liulei-spring-cloud-admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-demo?Unicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

shiro:
  hashAlgorithmName: md5
  hashIterations: 2

