spring:
  application:
    name: liulei-spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pickULL/liulei-cloud-config.git  # 远程git仓库的地址
          username: pickULL  # 以及相应的账户名
          password: liu19930121  # 和密码
          basedir: F:\ideaProjects\cloudConfig  # 可以使用这个配置项来指定本地git仓库的路径
          search-paths: /** # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
server:
  port: 8974
